name: 'cargo-bloat'
description: 'Track rust bloat across builds'
author: 'orf'
branding:
  icon: box
  color: blue
inputs:
  token:
    description: 'Github token to use, defaults to github.token'
    required: false
    default: ${{ github.token }}
  bloat_args:
    description: 'Custom arguments to pass to cargo bloat'
    required: false
  tree_args:
    description: 'Custom arguments to pass to cargo tree'
    required: false
  by_function:
    description: 'If set, display per-function bloat instead of per-crate bloat.'
    required: false
  exclude_packages:
    description: 'Packages to exclude from running cargo bloat onto.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
